import type { PdfLocale } from '@/lib/pdf/pdf-locale'

/**
 * Page-2 legal / commercial terms for offer PDFs — by PDF locale.
 * (Offer `paymentTerms.text` from DB is often Hebrew-only; PDF follows UI locale.)
 */
const HE = [
  'תנאים כלליים — הצעת מחיר',
  'Pashkovsky Group · פתרונות אלומיניום',
  '',
  '1. תנאי ביצוע',
  '1. תחילת ייצור מותנית בביצוע מדידות סופיות בשטח, לאחר סיום טיח, חיפוי וריצוף בנקודות העיגון.',
  '2. באחריות המזמין לספק חשמל קבוע או זמני ותאורה מספקת באזור ההתקנה, וכן גישה נוחה ובטוחה לפריקת סחורה.',
  '3. העלאת סחורה לקומות, שימוש במנוף או עגורן, ואספקת פיגומים תקניים — באחריות המזמין ועל חשבונו.',
  '4. אזור ההתקנה יימסר נקי מפסולת בניין ופנוי מעבודות קבלנים אחרים.',
  '5. בפרגולות חשמליות ותאורה — הבאת נקודת חשמל וחיבור ללוח הם באחריות חשמלאי מוסמך מטעם המזמין.',
  '6. המחירים כוללים אספקה והתקנה, אלא אם צוין אחרת במפורש.',
  '',
  '2. לוח זמנים ואספקה',
  '7. זמן אספקה והתקנה: עד 35 ימי עבודה ממועד אישור תוכניות סופי, לאחר מוכנות השטח וקבלת המקדמה — המאוחר מביניהם.',
  '8. החברה לא תישא באחריות לעיכובים הנובעים מכוח עליון, מלחמה, עיכובי נמל, שביתות, או אי-מוכנות האתר מצד המזמין.',
  '9. שינויים בהזמנה לאחר אישורה עשויים לגרור עדכון מחיר ולוח זמנים, ויאושרו בכתב בלבד.',
  '',
  '3. תנאי תשלום',
  'התשלום מחולק לשלושה שלבים:',
  '%\tשלב\tמועד תשלום',
  '10%\tמקדמה\tבעת אישור ההזמנה',
  '90%\tגמר תשלום\tבסיום ההתקנה, לפני עזיבת הצוות',
  '',
  'אופציות תשלום: העברה בנקאית · אשראי · שיקים · הוראת קבע — בהתאם למדיניות החברה.',
  '10. לאחר תחילת ייצור מוצר המותאם אישית לפי מידות הלקוח — לא יינתן החזר כספי.',
  '',
  '4. רישוי ואחריות משפטית',
  '11. אחריות על היתרי בנייה ואישורי קונסטרוקטור לעומסי המבנה ולנקודות העיגון — חלה על המזמין בלבד.',
  '12. Pashkovsky Group אינה אחראית לנושאי רישוי מול הרשות המקומית. המזמין מתחייב לבצע את כל הבירורים הנדרשים.',
  '13. החברה אינה אחראית לנזקים בלתי צפויים כגון: פיצוצי צנרת, נזקי מים, גז, חשמל — באחריות המזמין להודיע מראש על מצבים אלו.',
  '14. על המזמין להודיע לחברת הביטוח שלו על התקנת מוצרי החברה, על מנת שיכוסו בפוליסת הביטוח.',
  '15. הצעה זו מהווה הערכה בלבד ואינה מחייבת עד לחתימה על הזמנה רשמית.',
  '',
  '5. אחריות על המוצרים',
  'מוצר / רכיב\tתקופת אחריות',
  'פרגולות אלומיניום — צבע, קונסטרוקציה\t7 שנים',
  'סנטף BH (גג קבוע)\t7 שנים',
  'סנטף פוליקרבונט\t2 שנים',
  'מרזבים ואיטום\tשנה ראשונה',
  'ציוד חשמלי (מאווררים, LED)\tשנה אחת',
  'זכוכית מחוסמת\tשנה אחת',
  '',
  '16. האחריות חלה על פגמי ייצור וחומר בלבד. אינה כוללת נזקי מזג אוויר חריג, שימוש לא נכון, או שינויים שבוצעו על-ידי צד שלישי.',
  '',
  'Pashkovsky Group · פתרונות אלומיניום · 052-449-4848 · office@pashkovskygroup.com',
].join('\n')

const EN = [
  'General terms — commercial offer',
  'Pashkovsky Group · aluminum solutions',
  '',
  '1. Execution conditions',
  '1. Production starts only after final on-site measurements, once plaster, cladding and flooring are finished at anchoring points.',
  '2. The client must provide permanent or temporary power and adequate lighting at the installation area, plus safe and convenient access for unloading.',
  '3. Hoisting to upper floors, crane/lift use, and compliant scaffolding — client’s responsibility and cost.',
  '4. The installation area must be clear of construction waste and free of other contractors’ work.',
  '5. For electric pergolas and lighting — bringing power to the board is the responsibility of a licensed electrician appointed by the client.',
  '6. Prices include supply and installation unless explicitly stated otherwise.',
  '',
  '2. Schedule and delivery',
  '7. Supply and installation: up to 35 working days from approval of final drawings, after site readiness and receipt of deposit — whichever is later.',
  '8. The company is not liable for delays due to force majeure, war, port delays, strikes, or site unreadiness on the client’s side.',
  '9. Changes after order approval may require price and schedule updates and must be approved in writing only.',
  '',
  '3. Payment terms',
  'Payment is in three stages:',
  '%\tStage\tWhen to pay',
  '10%\tDeposit\ton order approval',
  '90%\tFinal payment\ton completion of installation, before the crew leaves',
  '',
  'Payment options: bank transfer · credit card · checks · standing order — per company policy.',
  '10. After production begins of a product custom-made to the client’s measurements — no monetary refund.',
  '',
  '4. Permits and legal liability',
  '11. Building permits and structural engineer approvals for loads and anchor points — client’s sole responsibility.',
  '12. Pashkovsky Group is not responsible for licensing with the local authority. The client undertakes to perform all required checks.',
  '13. The company is not liable for unforeseen damage such as plumbing bursts, water, gas, or electrical damage — the client must report such conditions in advance.',
  '14. The client must inform their insurer about installation of the company’s products so they are covered by the policy.',
  '15. This offer is an estimate only and is not binding until a formal order is signed.',
  '',
  '5. Product warranty',
  'Product / component\tWarranty period',
  'Aluminum pergolas — paint, structure\t7 years',
  'Polycarbonate BH (fixed roof)\t7 years',
  'Polycarbonate\t2 years',
  'Gutters and sealing\tfirst year',
  'Electrical equipment (fans, LED)\tone year',
  'Tempered glass\tone year',
  '',
  '16. Warranty covers manufacturing and material defects only. It excludes extreme weather damage, improper use, or modifications by a third party.',
  '',
  'Pashkovsky Group · aluminum solutions · 052-449-4848 · office@pashkovskygroup.com',
].join('\n')

const RU = [
  'Общие условия — коммерческое предложение',
  'Pashkovsky Group · алюминиевые решения',
  '',
  '1. Условия выполнения работ',
  '1. Запуск производства возможен только после финальных замеров на объекте, по завершении штукатурки, облицовки и напольного покрытия в точках крепления.',
  '2. Заказчик обеспечивает постоянное или временное электроснабжение и достаточное освещение зоны монтажа, а также удобный и безопасный подъезд для разгрузки.',
  '3. Подъём материала на этажи, работа крана/лифта и выставление нормативных лесов — за счёт и под ответственность заказчика.',
  '4. Площадь монтажа передаётся без строительного мусора и свободной от работ других подрядчиков.',
  '5. Для электрических пергол и освещения — подвод силы и подключение к щиту выполняет уполномоченный электрик заказчика.',
  '6. Цены включают поставку и монтаж, если иное явно не оговорено.',
  '',
  '2. Сроки и поставка',
  '7. Срок поставки и монтажа: до 35 рабочих дней с даты утверждения финальных чертежей, после готовности объекта и получения предоплаты — по более поздней дате.',
  '8. Компания не отвечает за задержки из-за форс-мажора, военных действий, задержек в порту, забастовок или неготовности объекта со стороны заказчика.',
  '9. Изменения заказа после утверждения могут повлечь пересмотр цены и сроков и допускаются только в письменной форме.',
  '',
  '3. Условия оплаты',
  'Оплата в три этапа:',
  '%\tЭтап\tСрок оплаты',
  '10%\tАванс\tпри утверждении заказа',
  '90%\tОкончательный платёж\tпо завершении монтажа, до отъезда бригады',
  '',
  'Способы оплаты: банковский перевод · карта · чеки · постоянное поручение — по политике компании.',
  '10. После начала производства изделия по индивидуальным размерам заказчика денежный возврат не производится.',
  '',
  '4. Разрешения и юридическая ответственность',
  '11. Разрешения на строительство и заключения инженера по нагрузкам и точкам крепления — только обязанность заказчика.',
  '12. Pashkovsky Group не отвечает за согласования с местными органами власти. Заказчик обязуется выполнить все необходимые проверки.',
  '13. Компания не несёт ответственности за непредвиденные повреждения (прорыв трубопровода, вода, газ, электрика) — заказчик заранее информирует о таких условиях.',
  '14. Заказчик обязан уведомить свою страховую компанию об установке продукции, чтобы она была включена в полис.',
  '15. Настоящее предложение носит оценочный характер и обязательно только после подписания официального заказа.',
  '',
  '5. Гарантия на продукцию',
  'Изделие / компонент\tСрок гарантии',
  'Алюминиевые перголы — покраска, конструкция\t7 лет',
  'Поликарбонат BH (фиксированная кровля)\t7 лет',
  'Поликарбонат\t2 года',
  'Водостоки и герметизация\tпервый год',
  'Электрооборудование (вентиляторы, LED)\tодин год',
  'Закалённое стекло\tодин год',
  '',
  '16. Гарантия распространяется только на дефекты производства и материала. Не покрывает экстремальную погоду, неправильное использование или вмешательство третьих лиц.',
  '',
  'Pashkovsky Group · алюминиевые решения · 052-449-4848 · office@pashkovskygroup.com',
].join('\n')

/** Serbian PDF: same legal content as English until dedicated translation exists. */
const SR = EN

export const OFFER_TERMS_BODIES: Record<PdfLocale, string> = {
  he: HE,
  en: EN,
  ru: RU,
  sr: SR,
}
